all: example

clean: cleanall

example:
	(cd chapter03; make )
	(cd chapter04; make )
	(cd chapter05; make )
	(cd chapter06; make )
	(cd chapter07; make )
	(cd chapter09; make )
	(cd chapter10; make )
	(cd chapter11; make )
	(cd appendix_a; make )

cleanall:
	(cd chapter03; make clean )
	(cd chapter04; make clean )
	(cd chapter05; make clean )
	(cd chapter06; make clean )
	(cd chapter07; make clean )
	(cd chapter09; make clean )
	(cd chapter10; make clean )
	(cd chapter11; make clean )
	(cd appendix_a; make clean )

